name: Package Application with Pyinstaller

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r src/requirements.txt

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: 'src'

      - uses: actions/upload-artifact@v2
        with:
          name: Plex.Auto.Shutdown
          path: src/dist/windows
