name: Package Application with Pyinstaller

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: 'src'

      - uses: actions/upload-artifact@v3
        with:
          name: Plex.Auto.Shutdown
          path: src/dist/windows
