name: Package Application with Pyinstaller

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
        with:
          path: '.'

      - uses: actions/upload-artifact@v3
        with:
          name: Plex.Auto.Shutdown
          path: ./dist/windows

      - name: Upload binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/windows/Plex.Auto.Shutdown.exe
          asset_name: Plex.Auto.Shutdown.exe
          tag: ${{ github.ref }}
